# This file hold all the configuration parameters specifically
# relating to the forklift and its dimensions/specifications
# All units should be in SI unless otherwise specified

# General Dimensions
forklift:
    body:
        length: 2.5601
        width: 1.3599
        total: 3.5659
        front_axle_to_back_of_forks: 0.4600
        base_to_clamp: 1.4658
        base_to_back: 1.9472
    wheels:
        front_length: 0.6921
        front_width: 0.2159
        back_length: 0.4445
        back_width: 0.1778
        front_axle_to_back_axle: 1.7249
        front_axle_width: 1.1440
    clamp:
        inner_width: 1.1059
        thickness: 0.0432
        short_length: 0.6960
        long_length: 1.0058
    steering:
        min_angle: -1.3089969 # 75 degrees (in radians)
        max_angle: 1.3089969 # 75 degrees (in radians)
    
# Frame transform parameters
front_axle_middle:
    pose:
        x: 0.0
        y: 0.0
        z: 0.0
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
    frames:
        frame_id: "base_link"
        child_frame_id: "front_axle_middle_link"
        
clamp_short_arm:
    pose:
        x: 1.370
        y: -0.520
        z: 0.0
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
    frames:
        frame_id: "base_link"
        child_frame_id: "clamp_short_arm"
