# Transforms for the IMU from the robot's base_link frame

imu0:
    pose:
        x: -1.126
        y: 0.0
        z: 1.857
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
    frames:
        frame_id: "base_link"
        child_frame_id: "imu0_link"
        
imu1:
    pose:
        x: -1.545
        y: -0.477
        z: 1.857
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
    frames:
        frame_id: "base_link"
        child_frame_id: "imu1_link"
        
lidar0_imu:
    pose:
        x: 0.0
        y: 0.0
        z: 0.0
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
    frames:
        frame_id: "lidar0_link"
        child_frame_id: "lidar0_imu"
        
lidar1_imu:
    pose:
        x: 0.0
        y: 0.0
        z: 0.0
        qx: 0.0
        qy: 0.0
        qz: 0.0
        qw: 1.0
    frames:
        frame_id: "lidar1_link"
        child_frame_id: "lidar1_imu"
    
